Repository aurora-is-near/doc.aurora.dev, pull requests merged in 2021-06, with the labels that each got.

#13 Use account references instead of explicit addresses in Truffle tutorial
  content/develop/start/truffle.md
Labels: documentation, enhancement

#14 Update MetaMask screenshot with ETH currency
  content/_img/metamask_create_aurora_rpc.png
Labels: bug, documentation

#15 Learn-level connecting MetaMask; bridging ETH tutorial
  content/_img/bridge_add_aurora_to_metamask.png
  content/_img/bridge_connect_wallet.png
  content/_img/bridge_connect_with_metamask.png
  content/_img/bridge_ropsten_connected.png
  content/_img/bridge_send_one_eth_to_aurora.png
  content/_img/bridge_send_one_eth_to_aurora_completed.png
  content/_img/bridge_send_one_eth_to_aurora_confirm.png
  content/_img/bridge_send_one_eth_to_aurora_metamask_confirm.png
  content/_img/bridge_send_one_eth_to_aurora_processing_transfer.png
  content/_img/bridge_send_one_eth_to_aurora_waiting.png
  content/_img/bridge_switch_ropsten_to_aurora.png
  content/_img/metamask_aurora_testnet.png
  content/_img/metamask_aurora_testnet_with_one_eth.png
  content/_img/metamask_ropsten_network_select.png
  content/_img/metamask_two_ropsten_eth.png
  content/learn/bridge/eth.md
  content/learn/connect/metamask.md
  mkdocs.yml
Labels: documentation, enhancement

#17 Add discussion about gas on Aurora
  content/develop/compat/evm.md
  content/develop/compat/gas.md
  content/develop/compat/rpc.md
  mkdocs.yml
Labels: documentation, enhancement

#19 Standardize network names to use lowercase n
  content/develop/changelog.md
  content/develop/compat/gas.md
  content/develop/networks.md
  content/develop/roadmap.md
  content/develop/start/metamask.md
  content/develop/start/truffle.md
Labels: bug, documentation

#16 Feature/hardhat
  content/develop/start/hardhat.md
  mkdocs.yml
Labels: documentation, enhancement

#22 Additional linter checks: Capitalization style and spelling
  .github/linters/.markdown-lint.yml
  .github/workflows/linter.yaml
  content/develop/faq.md
  content/develop/roadmap.md
  content/develop/start/hardhat.md
  content/develop/start/metamask.md
  content/develop/start/truffle.md
  content/learn/bridge/eth.md
  content/learn/connect/metamask.md
Labels: Continuous Integration, enhancement
