Repository aurora-is-near/doc.aurora.dev, pull requests merged in 2021-05, with the labels that each got.

#2 Make linter allow longer lines
  .github/linters/.markdown-lint.yml
Labels: enhancement

#3 Update FAQ
  content/develop/faq.md
  content/develop/networks.md
  content/develop/roadmap.md
Labels: documentation, enhancement

#4 Remove filler text.
  content/develop/start/hardhat.md
  content/develop/start/metamask.md
  content/develop/start/truffle.md
  content/learn/bridge/erc-20.md
  content/learn/bridge/eth.md
  content/learn/connect/metamask.md
  content/learn/connect/walletconnect.md
  content/learn/deploy/hardhat.md
  content/learn/deploy/remix.md
  content/learn/deploy/truffle.md
  content/learn/interact/remix.md
Labels: documentation

#5 Update BLOCKHASH documentation to match current implementation
  content/develop/compat/evm.md
Labels: bug, documentation

#8 GitHub action to deploy docs on push to master
  .github/workflows/builds.yml
Labels: Continuous Integration, enhancement

#10 Do not force push to gh-pages in automated deploy
  .github/workflows/builds.yaml
Labels: Continuous Integration, enhancement

#9 Fix linter errors
  content/develop/changelog.md
  content/develop/faq.md
  content/develop/start/truffle.md
  content/learn/interact/remix.md
Labels: Continuous Integration, bug

#11 Simple MetaMask tutorial
  content/_img/metamask_add_token.png
  content/_img/metamask_add_token_account2.png
  content/_img/metamask_add_token_button.png
  content/_img/metamask_add_token_confirm.png
  content/_img/metamask_choose_network.png
  content/_img/metamask_create_aurora_rpc.png
  content/_img/metamask_my_token.png
  content/_img/metamask_my_token_sent_account1.png
  content/_img/metamask_send_my_token.png
  content/_img/metamask_send_my_token_confirm.png
  content/_img/remix_connect_with_metamask.png
  content/_img/remix_deploy_contract.png
  content/_img/remix_deploy_contract_confirmed.png
  content/_img/remix_deploy_contract_metamask_confirm.png
  content/_img/remix_injected_web3.png
  content/_img/remix_new_file.png
  content/_img/remix_solidity_compile.png
  content/develop/start/metamask.md
  mkdocs.yml
Labels: documentation, enhancement

#12 Truffle example
  content/_img/truffle_nft_example.png
  content/develop/start/truffle.md
  mkdocs.yml
Labels: documentation, enhancement
